import { registry } from '../swagger/registry';
import { SWAGGER_TAGS } from '../swagger/swagger.tags';
import { RESPONSE_SCHEMAS } from '../swagger/swagger.responses';
import { z } from 'zod';

/**
 * Payment API Documentation (Razorpay Integration)
 */

// POST /api/v1/payments/create-order
registry.registerPath({
  method: 'post',
  path: '/payments/create-order',
  summary: 'Create Wallet Top-up Order',
  description: 'Creates a pending transaction in the database and initiates a Razorpay Order. The generated Order ID should be passed to the Razorpay checkout overlay on the mobile/web frontend.',
  tags: [SWAGGER_TAGS.PAYMENT],
  security: [{ firebaseAuth: [] }],
  request: {
    body: {
      content: {
        'application/json': {
          schema: z.object({
            amount: z.number().positive().describe('Top-up amount in INR (e.g. 500)'),
          }),
        },
      },
    },
  },
  responses: {
    201: RESPONSE_SCHEMAS.SUCCESS(
      z.object({
        id: z.string().describe('Razorpay Order ID (e.g. order_LKjnsd8912)'),
        entity: z.string().describe('Entity name (always "order")'),
        amount: z.number().describe('Amount in smallest currency unit (e.g. paise: INR 500 = 50000)'),
        amount_paid: z.number().describe('Amount paid so far'),
        amount_due: z.number().describe('Remaining amount due'),
        currency: z.string().describe('Currency code (default "INR")'),
        receipt: z.string().describe('Receipt ID generated for this transaction'),
        status: z.string().describe('Status of the order (e.g. "created")'),
        attempts: z.number().describe('Number of payment attempts made'),
        notes: z.any().describe('Notes/metadata attached to the order'),
        created_at: z.number().describe('Epoch timestamp of order creation'),
      }),
      'Razorpay Top-up Order created successfully'
    ),
    401: RESPONSE_SCHEMAS.ERROR('Unauthorized'),
    400: RESPONSE_SCHEMAS.ERROR('Invalid top-up amount'),
  },
});

// POST /api/v1/payments/verify
registry.registerPath({
  method: 'post',
  path: '/payments/verify',
  summary: 'Verify Razorpay Payment Signature',
  description: 'Verifies the cryptographic signature generated by Razorpay Checkout. If valid, marks the transaction as successful and credits the authenticated user\'s wallet.',
  tags: [SWAGGER_TAGS.PAYMENT],
  security: [{ firebaseAuth: [] }],
  request: {
    body: {
      content: {
        'application/json': {
          schema: z.object({
            orderId: z.string().min(1).describe('The Razorpay Order ID returned from create-order API'),
            paymentId: z.string().min(1).describe('The Razorpay Payment ID returned from Checkout callback'),
            signature: z.string().min(1).describe('The Razorpay cryptographic Signature returned from Checkout callback'),
          }),
        },
      },
    },
  },
  responses: {
    200: RESPONSE_SCHEMAS.SUCCESS(
      z.object({
        message: z.string().describe('Confirmation message'),
      }),
      'Payment verified and wallet credited successfully'
    ),
    400: RESPONSE_SCHEMAS.ERROR('Cryptographic signature verification failed'),
    404: RESPONSE_SCHEMAS.ERROR('Transaction not found matching the orderId'),
    401: RESPONSE_SCHEMAS.ERROR('Unauthorized'),
  },
});

// POST /api/v1/payments/refund
registry.registerPath({
  method: 'post',
  path: '/payments/refund',
  summary: 'Refund a Transaction',
  description: 'Processes a refund for a previously successful transaction through the Razorpay gateway and creates a refund transaction log.',
  tags: [SWAGGER_TAGS.PAYMENT],
  security: [{ firebaseAuth: [] }],
  request: {
    body: {
      content: {
        'application/json': {
          schema: z.object({
            transactionId: z.string().min(1).describe('The internal MongoDB Transaction ID to refund'),
            amount: z.number().positive().optional().describe('Optional amount to refund (defaults to full transaction amount if omitted)'),
            reason: z.string().optional().describe('Reason for refunding the payment'),
          }),
        },
      },
    },
  },
  responses: {
    200: RESPONSE_SCHEMAS.SUCCESS(
      z.object({
        id: z.string().describe('Razorpay Refund ID (e.g. rfnd_LKjnsd8912)'),
        entity: z.string().describe('Entity name (always "refund")'),
        amount: z.number().describe('Amount refunded in smallest currency unit'),
        currency: z.string().describe('Currency code'),
        payment_id: z.string().describe('The associated Razorpay Payment ID that was refunded'),
        status: z.string().describe('Refund status (e.g. "processed")'),
        created_at: z.number().describe('Epoch timestamp of refund creation'),
      }),
      'Payment refunded successfully'
    ),
    400: RESPONSE_SCHEMAS.ERROR('Validation failed or only successful transactions can be refunded'),
    404: RESPONSE_SCHEMAS.ERROR('Transaction not found'),
    401: RESPONSE_SCHEMAS.ERROR('Unauthorized'),
  },
});

// POST /api/v1/payments/webhook
registry.registerPath({
  method: 'post',
  path: '/payments/webhook',
  summary: 'Razorpay Webhook Callback',
  description: 'Webhook endpoint invoked by Razorpay servers for asynchronous payment events (success, refund updates, failed captures). Uses custom signature headers to verify payload integrity.',
  tags: [SWAGGER_TAGS.PAYMENT],
  request: {
    body: {
      content: {
        'application/json': {
          schema: z.any().describe('Raw webhook JSON event payload from Razorpay'),
        },
      },
    },
  },
  responses: {
    200: RESPONSE_SCHEMAS.SUCCESS(
      z.object({}),
      'Webhook received and verified successfully'
    ),
  },
});
